---
- name: Update web servers
  hosts: n2
  become: yes
  tasks:
  - name: Ensure Git HTTP Installed
    yum:
      name: git
      state: installed

  - name: Ensure food Updated
    git:
      repo: https://github.com/bbanesh/https-github.com-ravi2krishna-food.git
      dest: /var/www/html 

... 
